// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieyuoeoskuujnqfmkpnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlleXVvZW9za3V1am5xZm1rcG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDQyMDAsImV4cCI6MjA2MTg4MDIwMH0.b0f9aI_t4H8zjLUGvPkKuvaM8OMxbxYMQuROUTEIpYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});